[ -z "$PS1" ] && return

if [ -f ~/.bashrc ]; then
          . ~/.bashrc
fi

if [ ! $DISPLAY ] ; then
    if [ "$SSH_CLIENT" ] ; then
        export DISPLAY=`echo $SSH_CLIENT|cut -f1 -d\ `:0.0
    fi
fi
