#! /bin/sh
### BEGIN INIT INFO
# Provides:          ezstream
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ezstream
# Description:       Starts the ezstream
### END INIT INFO
#
# ezstream
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/ezstream
NAME=ezstream
DESC="command line source client for Icecast"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

# Defaults
CONFIGFILE=/etc/icecast2/ezstream.xml
USERID=icecast2
GROUPID=icecast
PIDFILE=/var/run/ezstream.pid

set -e

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"

	start-stop-daemon --start --quiet --chuid $USERID:$GROUPID \
		--background --make-pidfile --pidfile $PIDFILE \
		--exec $DAEMON -- -n -c $CONFIGFILE > /dev/null
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --oknodo --quiet --pidfile $PIDFILE
	log_end_msg $?
	;;
  reload|force-reload)
	log_daemon_msg "Reloading $DESC configuration" "$NAME"
	start-stop-daemon --stop --signal 1 --quiet --exec $DAEMON
	log_end_msg $?
	;;
  restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
	start-stop-daemon --stop --oknodo --quiet --pidfile $PIDFILE
	start-stop-daemon --start --quiet --chuid $USERID:$GROUPID \
		--background --make-pidfile --pidfile $PIDFILE \
		--exec $DAEMON -- -n -c $CONFIGFILE > /dev/null
	log_end_msg $?
	;;
  status)
	status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
